version: '3'
services:
  lvef.frontend:
    env_file: .env
    build:
      context: ./
      dockerfile: frontend/docker/Dockerfile
    ports:
      - '${VITE_FRONTEND_PORT:-3454}:3454'
    networks:
      - proxynet
  lvef.backend:
    env_file: .env
    build:
      context: ./
      dockerfile: backend/docker/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${BACKEND_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './backend:/var/www/html'
networks:
  proxynet:
    driver: bridge
volumes:
  lvef-mysql:
    driver: local
