version: '3'
services:
  lvef.frontend:
    env_file: .env
    build:
      context: ./
      dockerfile: frontend/docker/Dockerfile
    ports:
      - '${VITE_FRONTEND_PORT:-3454}:3454'
    networks:
      - proxynet
    volumes:
      - './frontend:/app'
  lvef.backend:
    env_file: .env
    build:
      context: ./
      dockerfile: backend/docker/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${BACKEND_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './backend:/var/www/html'
    networks:
      - proxynet
    depends_on:
      - lvef.mysql
  lvef.mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'lvef-mysql:/var/lib/mysql'
      - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - proxynet
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
networks:
  proxynet:
    driver: bridge
volumes:
  lvef-mysql:
    driver: local
